export const DEFAULT_PREVIDENCIARY_TERMS = [
  "previdenciario",
  "beneficio",
  "aposentadoria por idade do segurado especial",
  "aposentadoria por idade rural",
  "aposentadoria por idade urbana",
  "pensao por morte urbana",
  "pensao por morte rural",
  "salario-maternidade urbano",
  "salario-maternidade rural",
  "beneficio por incapacidade urbano",
  "beneficio por incapacidade rural",
  "auxilio-doenca",
  "aposentadoria por invalidez",
  "beneficio assistencial",
  "LOAS",
  "BPC idoso",
  "BPC pessoa com deficiencia",
  "BPC PCD",
] as const;

export const TRF5_CE_ORGAOS_JULGADORES = [
  "PRESIDÊNCIA DA 1ª TURMA RECURSAL DO CEARÁ",
  "PRESIDÊNCIA DA 2ª TURMA RECURSAL DO CEARÁ",
  "PRESIDÊNCIA DA 3ª TURMA RECURSAL DO CEARÁ",
  "1ª RELATORIA DA 1ª TURMA RECURSAL DO CEARÁ",
  "2ª RELATORIA DA 1ª TURMA RECURSAL DO CEARÁ",
  "3ª RELATORIA DA 1ª TURMA RECURSAL DO CEARÁ",
  "1ª RELATORIA DA 2ª TURMA RECURSAL DO CEARÁ",
  "2ª RELATORIA DA 2ª TURMA RECURSAL DO CEARÁ",
  "3ª RELATORIA DA 2ª TURMA RECURSAL DO CEARÁ",
  "1ª RELATORIA DA 3ª TURMA RECURSAL DO CEARÁ",
  "2ª RELATORIA DA 3ª TURMA RECURSAL DO CEARÁ",
  "3ª RELATORIA DA 3ª TURMA RECURSAL DO CEARÁ",
] as const;